#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'

config_path = File.join(File.expand_path(File.dirname(__FILE__)), '..', 'MY EFI', 'CLOVER', 'config.plist')

require_relative 'lib/clean_config'

CleanConfig.new(config_path).clean!
puts "Done!"
