#!/usr/bin/env ruby

require 'plist'
require 'json'

config_path = File.join(File.expand_path(File.dirname(__FILE__)), '..', 'MY EFI', 'CLOVER', 'config.plist')
result = Plist.parse_xml(config_path)

GENERATE_ME = "{{GENERATE ME}}"

result['SMBIOS']['BoardSerialNumber'] = GENERATE_ME
result['SMBIOS']['SerialNumber'] = GENERATE_ME
result['SMBIOS']['SmUUID'] = GENERATE_ME
result['RtVariables']['MLB'] = "{{PASTE BOARD SERIAL NUMBER HERE}}"

result.save_plist(config_path)
puts "Done!"
